### ISSUE TITLE
Encode/Decode Lists

### ISSUE THREAD

**Issue by frankai** [rajdeep/proton#52] opened 2020-08-07 15:10 UTC
Hello! Congratulations and thanks for this great UITextView extension. 

It seems that lists are not encoded/decoded yet, do you think that will be supported soon? ;)

Best regards,
Franky

**Comment by rajdeep** [comment] 2020-08-07 22:54
thanks, @frankai for your comment. Glad you liked the framework.

Encoding and decoding is not included in Proton by design. This is so that there's no enforced limitations on consumers to be able to use Proton the way they like. Moreover, the kind of content that can be created by Proton entirely depends on consumer, so the best I can do is to provide a mechanism to get the content in native attributed string format and leave it up to the consumers to encode/decode their objects as they like. I understand encoding/decoding is very important and that is why the example app shows how content may be encoded/decoded.

Having said that, I do plan to create a helper class that allows to convert an object representation of list to attributed string, and back. This helper object can then be used by consumers to encode/decode the data in the format they like to. Lists is an internal implementation to Proton, so it makes sense to provide this helper.

Hope this addresses your query.

**Comment by frankai** [comment] 2020-08-08 14:28
Hi!
Yes! That helper really would be great!

Best regards,
Frankai

**Comment by YoX89** [comment] 2020-10-21 09:38
Hi!

Do you have any idea when you'll have time to do this? Is there anything I can help with perhaps?

I've made my own encoding/decoding of lists but it feels a bit hacky because I need to know about the internal states of the framework to make it work, just as you said.

Thanks!
Jonathan

**Comment by rajdeep** [comment] 2020-10-21 10:22
hi @YoX89,
Unfortunately I have not been able to find time to prioritise this. My focus has been on improving performance and I'll likely be spending time in near future on trying to get better performance in Proton. Lists has certainly been one of the more complex features to develop, so I can understand the challenges you might have run into. Given that there are now at least 2 people who can benefit from this, I'll try to manage this in coming few weeks. 🙂

**Comment by rajdeep** [comment] 2020-12-15 10:21
`ListParser` has been implemented and merged to `master`. Please refer to [documentation](https://rajdeep.github.io/proton/Structs/ListParser.html) for details.

**Closed by rajdeep** 2020-12-15 10:21 UTC
